### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-Dewinster#3]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by Dewinster** [comment]
The algorithm is Bubble sort, but after Googling Quick sort should be a better implementation.
https://nl.wikipedia.org/wiki/Quicksort

**Comment by dvberkel** [comment]
What do you mean by better?

**Comment by Dewinster** [comment]
Better on performance like: Speed and efficiency
